# Generated by Django 2.2.7 on 2019-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('meter_no', models.CharField(max_length=1)),
                ('gps', models.CharField(max_length=50)),
                ('correct_date', models.DateField()),
                ('correction_needed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
