# Generated by Django 2.2.7 on 2019-11-12 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='meter_no',
            field=models.CharField(max_length=100),
        ),
    ]
