# Generated by Django 2.2.7 on 2019-11-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191112_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationdetails',
            name='correct_date',
        ),
        migrations.RemoveField(
            model_name='stationdetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stationdetails',
            name='location',
        ),
        migrations.RemoveField(
            model_name='stationdetails',
            name='meter_no',
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='meter_drift',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
