# Generated by Django 2.2.7 on 2019-11-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191125_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='meter_drift',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
