# Generated by Django 2.2.7 on 2019-11-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_stationdetails_station_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdetails',
            name='dateofchecking',
            field=models.CharField(default='Null', max_length=10),
        ),
    ]
