# Generated by Django 2.2.7 on 2019-12-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191129_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='dateofchecking',
            field=models.DateTimeField(default='Null', max_length=10),
        ),
    ]
