# Generated by Django 2.2.7 on 2019-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20191203_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='dateofchecking',
            field=models.DateTimeField(max_length=10),
        ),
    ]
