# Generated by Django 2.2.7 on 2019-12-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20191203_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='dateofchecking',
            field=models.DateField(auto_now_add=True),
        ),
    ]
