# Generated by Django 2.2.7 on 2019-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20191204_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staion_store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utility_name', models.CharField(max_length=25)),
                ('station_name', models.CharField(max_length=25)),
            ],
        ),
    ]
