# Generated by Django 2.2.7 on 2019-12-05 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_staion_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staion_store',
            new_name='Station_store',
        ),
    ]
