# Generated by Django 2.2.7 on 2019-12-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191205_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='station_store',
            name='location_name',
            field=models.CharField(default='Null', max_length=50),
        ),
    ]
