# Generated by Django 2.2.7 on 2019-12-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_station_store_location_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semlog_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Utility_Name', models.CharField(max_length=55)),
                ('Station_Name', models.CharField(max_length=65)),
                ('Location', models.CharField(max_length=65)),
                ('Description', models.CharField(max_length=65)),
                ('Meter_No', models.CharField(max_length=65)),
            ],
        ),
    ]
