# Generated by Django 2.2.7 on 2019-12-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191216_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdetails',
            name='Description',
            field=models.TextField(default='Null'),
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='Meter_no',
            field=models.CharField(default='Null', max_length=255),
        ),
    ]
