# Generated by Django 2.2.7 on 2019-12-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191217_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stationdetails',
            name='Description',
        ),
    ]
