# Generated by Django 2.2.7 on 2020-01-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20191223_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdetails',
            name='dateofupload',
            field=models.DateTimeField(default='NULL'),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='remarks',
            field=models.CharField(max_length=200),
        ),
    ]
