# Generated by Django 2.2.7 on 2020-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20200104_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='dateofupload',
            field=models.DateField(),
        ),
    ]
