# Generated by Django 2.2.7 on 2020-01-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20200104_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='dateofupload',
            field=models.DateField(blank=True),
        ),
    ]
