# Generated by Django 2.2.7 on 2020-01-04 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200104_1850'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StationDetails',
        ),
    ]
