# Generated by Django 2.2.7 on 2020-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_delete_stationdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=65)),
                ('Meter_no', models.CharField(max_length=255)),
                ('gps', models.CharField(max_length=50)),
                ('meter_drift', models.CharField(max_length=50)),
                ('meter_difference', models.CharField(max_length=55)),
                ('dateofchecking', models.DateField()),
                ('dateofupload', models.DateField()),
                ('correction_needed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=20)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
