# Generated by Django 2.2.7 on 2020-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20200104_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdetails',
            name='utility_name',
            field=models.CharField(default='NULL', max_length=255),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='station_name',
            field=models.CharField(max_length=255),
        ),
    ]
