# Generated by Django 2.2.7 on 2020-01-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20200104_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='dateofupload',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='gps',
            field=models.TimeField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='meter_difference',
            field=models.TimeField(max_length=55),
        ),
        migrations.AlterField(
            model_name='stationdetails',
            name='meter_drift',
            field=models.TimeField(max_length=50),
        ),
    ]
