# Generated by Django 2.2.7 on 2020-01-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20200106_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationdetails',
            name='dateofupload',
            field=models.DateTimeField(),
        ),
    ]
