# Generated by Django 2.2.7 on 2020-01-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20200106_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdetails',
            name='meter_status',
            field=models.CharField(default='NULL', max_length=15),
        ),
    ]
