# Generated by Django 2.1.15 on 2020-02-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_stationdetails_meter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationdetails',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
